# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: questgen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0equestgen.proto\x12\x08questgen\"\"\n\x0fQuestGenRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"$\n\x10QuestGenResponse\x12\x10\n\x08response\x18\x01 \x01(\t2V\n\x0fQuestGenService\x12\x43\n\x08QuestGen\x12\x19.questgen.QuestGenRequest\x1a\x1a.questgen.QuestGenResponse\"\x00\x42\x13Z\x11./pkg/questgen/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'questgen_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021./pkg/questgen/pb'
  _QUESTGENREQUEST._serialized_start=28
  _QUESTGENREQUEST._serialized_end=62
  _QUESTGENRESPONSE._serialized_start=64
  _QUESTGENRESPONSE._serialized_end=100
  _QUESTGENSERVICE._serialized_start=102
  _QUESTGENSERVICE._serialized_end=188
# @@protoc_insertion_point(module_scope)
