# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import questgen_pb2 as questgen__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in questgen_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuestGenServiceStub:
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QuestGen = channel.unary_unary(
                '/questgen.QuestGenService/QuestGen',
                request_serializer=questgen__pb2.QuestGenRequest.SerializeToString,
                response_deserializer=questgen__pb2.QuestGenResponse.FromString,
                _registered_method=True)
        self.AskQuestion = channel.unary_unary(
                '/questgen.QuestGenService/AskQuestion',
                request_serializer=questgen__pb2.AskQuestionRequest.SerializeToString,
                response_deserializer=questgen__pb2.AskQuestionResponse.FromString,
                _registered_method=True)


class QuestGenServiceServicer:
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def QuestGen(self, request, context):
        """Examiner: Generate questions from a paragraph of text (RAG pipeline)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskQuestion(self, request, context):
        """Student: Ask a question against indexed course material
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuestGenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QuestGen': grpc.unary_unary_rpc_method_handler(
                    servicer.QuestGen,
                    request_deserializer=questgen__pb2.QuestGenRequest.FromString,
                    response_serializer=questgen__pb2.QuestGenResponse.SerializeToString,
            ),
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=questgen__pb2.AskQuestionRequest.FromString,
                    response_serializer=questgen__pb2.AskQuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questgen.QuestGenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('questgen.QuestGenService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuestGenService:
    """── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def QuestGen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questgen.QuestGenService/QuestGen',
            questgen__pb2.QuestGenRequest.SerializeToString,
            questgen__pb2.QuestGenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/questgen.QuestGenService/AskQuestion',
            questgen__pb2.AskQuestionRequest.SerializeToString,
            questgen__pb2.AskQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
