# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import questgen_pb2 as questgen__pb2


class QuestGenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QuestGen = channel.unary_unary(
                '/questgen.QuestGenService/QuestGen',
                request_serializer=questgen__pb2.QuestGenRequest.SerializeToString,
                response_deserializer=questgen__pb2.QuestGenResponse.FromString,
                )


class QuestGenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QuestGen(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuestGenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QuestGen': grpc.unary_unary_rpc_method_handler(
                    servicer.QuestGen,
                    request_deserializer=questgen__pb2.QuestGenRequest.FromString,
                    response_serializer=questgen__pb2.QuestGenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questgen.QuestGenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuestGenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QuestGen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/questgen.QuestGenService/QuestGen',
            questgen__pb2.QuestGenRequest.SerializeToString,
            questgen__pb2.QuestGenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
