# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pb import intelligence_pb2 as intelligence__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in intelligence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.',
        RuntimeWarning,
    )


class IntelligenceServiceStub(object):
    """Unified query endpoint — any authenticated user calls this.
    The agent reads role, client_id, context_id to decide tool and scope.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
            '/intelligence.IntelligenceService/Ask',
            request_serializer=intelligence__pb2.IntelligenceRequest.SerializeToString,
            response_deserializer=intelligence__pb2.IntelligenceResponse.FromString,
            _registered_method=True,
        )


class IntelligenceServiceServicer(object):
    """Unified query endpoint — any authenticated user calls this.
    The agent reads role, client_id, context_id to decide tool and scope.
    """

    def Ask(self, request, context):
        """Unified query endpoint — any authenticated user calls this.
        The agent reads role, client_id, context_id to decide tool and scope.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligenceServiceServicer_to_server(servicer, server):
    from grpc import unary_unary_rpc_method_handler as unary_unary
    from grpc import method_service_handler as method_service
    rpc_method_handlers = {
        'Ask': grpc.unary_unary_rpc_method_handler(
            servicer.Ask,
            request_deserializer=intelligence__pb2.IntelligenceRequest.FromString,
            response_serializer=intelligence__pb2.IntelligenceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_service_handler(rpc_method_handlers) if hasattr(grpc, 'method_service_handler') else grpc.GenericMethodHandler(rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('intelligence.IntelligenceService', rpc_method_handlers)


class IntelligenceService(object):
    """Unified query endpoint — any authenticated user calls this.
    The agent reads role, client_id, context_id to decide tool and scope.
    """

    @staticmethod
    def Ask(request, target, options=(), channel_credentials=None,
            call_credentials=None, insecure=False, compression=None,
            wait_for_ready=None, timeout=None, metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.IntelligenceService/Ask',
            intelligence__pb2.IntelligenceRequest.SerializeToString,
            intelligence__pb2.IntelligenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )