# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intelligence.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'intelligence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12intelligence.proto\x12\x0cintelligence\"u\n\x14IntelligenceRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x12\n\ncontext_id\x18\x05 \x01(\t\"P\n\x15IntelligenceResponse\x12\x0e\n\x06answer\x18\x01 \x01(\t\x12\x11\n\ttool_used\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32`\n\x14IntelligenceService\x12H\n\x03\x41sk\x12\".intelligence.IntelligenceRequest\x1a#.intelligence.IntelligenceResponse\"\x00\x42\x15Z\x13./pkg/intelligence/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intelligence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\x13./pkg/intelligence/pb'
    _globals['_INTELLIGENCEREQUEST']._serialized_start = 32
    _globals['_INTELLIGENCEREQUEST']._serialized_end = 149
    _globals['_INTELLIGENCERESPONSE']._serialized_start = 151
    _globals['_INTELLIGENCERESPONSE']._serialized_end = 231
    _globals['_INTELLIGENCESERVICE']._serialized_start = 233
    _globals['_INTELLIGENCESERVICE']._serialized_end = 329
# @@protoc_insertion_point(module_scope)