// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: questgen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestGenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestGenRequest) Reset() {
	*x = QuestGenRequest{}
	mi := &file_questgen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestGenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestGenRequest) ProtoMessage() {}

func (x *QuestGenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questgen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestGenRequest.ProtoReflect.Descriptor instead.
func (*QuestGenRequest) Descriptor() ([]byte, []int) {
	return file_questgen_proto_rawDescGZIP(), []int{0}
}

func (x *QuestGenRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type QuestGenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestGenResponse) Reset() {
	*x = QuestGenResponse{}
	mi := &file_questgen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestGenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestGenResponse) ProtoMessage() {}

func (x *QuestGenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_questgen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestGenResponse.ProtoReflect.Descriptor instead.
func (*QuestGenResponse) Descriptor() ([]byte, []int) {
	return file_questgen_proto_rawDescGZIP(), []int{1}
}

func (x *QuestGenResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type AskQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`                    // The student's question
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"` // Optional: topic/subject scope for retrieval (e.g. "biology")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionRequest) Reset() {
	*x = AskQuestionRequest{}
	mi := &file_questgen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionRequest) ProtoMessage() {}

func (x *AskQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_questgen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionRequest.ProtoReflect.Descriptor instead.
func (*AskQuestionRequest) Descriptor() ([]byte, []int) {
	return file_questgen_proto_rawDescGZIP(), []int{2}
}

func (x *AskQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskQuestionRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

type AskQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionResponse) Reset() {
	*x = AskQuestionResponse{}
	mi := &file_questgen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionResponse) ProtoMessage() {}

func (x *AskQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_questgen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionResponse.ProtoReflect.Descriptor instead.
func (*AskQuestionResponse) Descriptor() ([]byte, []int) {
	return file_questgen_proto_rawDescGZIP(), []int{3}
}

func (x *AskQuestionResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_questgen_proto protoreflect.FileDescriptor

const file_questgen_proto_rawDesc = "" +
	"\n" +
	"\x0equestgen.proto\x12\bquestgen\"+\n" +
	"\x0fQuestGenRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\".\n" +
	"\x10QuestGenResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"O\n" +
	"\x12AskQuestionRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\"-\n" +
	"\x13AskQuestionResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer2\xa4\x01\n" +
	"\x0fQuestGenService\x12C\n" +
	"\bQuestGen\x12\x19.questgen.QuestGenRequest\x1a\x1a.questgen.QuestGenResponse\"\x00\x12L\n" +
	"\vAskQuestion\x12\x1c.questgen.AskQuestionRequest\x1a\x1d.questgen.AskQuestionResponse\"\x00B\x13Z\x11./pkg/questgen/pbb\x06proto3"

var (
	file_questgen_proto_rawDescOnce sync.Once
	file_questgen_proto_rawDescData []byte
)

func file_questgen_proto_rawDescGZIP() []byte {
	file_questgen_proto_rawDescOnce.Do(func() {
		file_questgen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_questgen_proto_rawDesc), len(file_questgen_proto_rawDesc)))
	})
	return file_questgen_proto_rawDescData
}

var file_questgen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_questgen_proto_goTypes = []any{
	(*QuestGenRequest)(nil),     // 0: questgen.QuestGenRequest
	(*QuestGenResponse)(nil),    // 1: questgen.QuestGenResponse
	(*AskQuestionRequest)(nil),  // 2: questgen.AskQuestionRequest
	(*AskQuestionResponse)(nil), // 3: questgen.AskQuestionResponse
}
var file_questgen_proto_depIdxs = []int32{
	0, // 0: questgen.QuestGenService.QuestGen:input_type -> questgen.QuestGenRequest
	2, // 1: questgen.QuestGenService.AskQuestion:input_type -> questgen.AskQuestionRequest
	1, // 2: questgen.QuestGenService.QuestGen:output_type -> questgen.QuestGenResponse
	3, // 3: questgen.QuestGenService.AskQuestion:output_type -> questgen.AskQuestionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_questgen_proto_init() }
func file_questgen_proto_init() {
	if File_questgen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_questgen_proto_rawDesc), len(file_questgen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_questgen_proto_goTypes,
		DependencyIndexes: file_questgen_proto_depIdxs,
		MessageInfos:      file_questgen_proto_msgTypes,
	}.Build()
	File_questgen_proto = out.File
	file_questgen_proto_goTypes = nil
	file_questgen_proto_depIdxs = nil
}
