// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: questgen.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuestGenService_QuestGen_FullMethodName    = "/questgen.QuestGenService/QuestGen"
	QuestGenService_AskQuestion_FullMethodName = "/questgen.QuestGenService/AskQuestion"
)

// QuestGenServiceClient is the client API for QuestGenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestGenServiceClient interface {
	// Examiner: Generate questions from a paragraph of text (RAG pipeline)
	QuestGen(ctx context.Context, in *QuestGenRequest, opts ...grpc.CallOption) (*QuestGenResponse, error)
	// Student: Ask a question against indexed course material
	AskQuestion(ctx context.Context, in *AskQuestionRequest, opts ...grpc.CallOption) (*AskQuestionResponse, error)
}

type questGenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestGenServiceClient(cc grpc.ClientConnInterface) QuestGenServiceClient {
	return &questGenServiceClient{cc}
}

func (c *questGenServiceClient) QuestGen(ctx context.Context, in *QuestGenRequest, opts ...grpc.CallOption) (*QuestGenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestGenResponse)
	err := c.cc.Invoke(ctx, QuestGenService_QuestGen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questGenServiceClient) AskQuestion(ctx context.Context, in *AskQuestionRequest, opts ...grpc.CallOption) (*AskQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskQuestionResponse)
	err := c.cc.Invoke(ctx, QuestGenService_AskQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestGenServiceServer is the server API for QuestGenService service.
// All implementations must embed UnimplementedQuestGenServiceServer
// for forward compatibility.
type QuestGenServiceServer interface {
	// Examiner: Generate questions from a paragraph of text (RAG pipeline)
	QuestGen(context.Context, *QuestGenRequest) (*QuestGenResponse, error)
	// Student: Ask a question against indexed course material
	AskQuestion(context.Context, *AskQuestionRequest) (*AskQuestionResponse, error)
	mustEmbedUnimplementedQuestGenServiceServer()
}

// UnimplementedQuestGenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuestGenServiceServer struct{}

func (UnimplementedQuestGenServiceServer) QuestGen(context.Context, *QuestGenRequest) (*QuestGenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QuestGen not implemented")
}
func (UnimplementedQuestGenServiceServer) AskQuestion(context.Context, *AskQuestionRequest) (*AskQuestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AskQuestion not implemented")
}
func (UnimplementedQuestGenServiceServer) mustEmbedUnimplementedQuestGenServiceServer() {}
func (UnimplementedQuestGenServiceServer) testEmbeddedByValue()                         {}

// UnsafeQuestGenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestGenServiceServer will
// result in compilation errors.
type UnsafeQuestGenServiceServer interface {
	mustEmbedUnimplementedQuestGenServiceServer()
}

func RegisterQuestGenServiceServer(s grpc.ServiceRegistrar, srv QuestGenServiceServer) {
	// If the following call panics, it indicates UnimplementedQuestGenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuestGenService_ServiceDesc, srv)
}

func _QuestGenService_QuestGen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestGenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestGenServiceServer).QuestGen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestGenService_QuestGen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestGenServiceServer).QuestGen(ctx, req.(*QuestGenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestGenService_AskQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestGenServiceServer).AskQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestGenService_AskQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestGenServiceServer).AskQuestion(ctx, req.(*AskQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuestGenService_ServiceDesc is the grpc.ServiceDesc for QuestGenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuestGenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "questgen.QuestGenService",
	HandlerType: (*QuestGenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuestGen",
			Handler:    _QuestGenService_QuestGen_Handler,
		},
		{
			MethodName: "AskQuestion",
			Handler:    _QuestGenService_AskQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "questgen.proto",
}
