// Code generated by protoc-gen-go. DO NOT EDIT.
// Manually written stub matching intelligence.proto
// source: intelligence.proto

package pb

// IntelligenceRequest is the unified query message sent by any authenticated user.
type IntelligenceRequest struct {
	Query     string `protobuf:"bytes,1,opt,name=query,proto3"      json:"query,omitempty"`
	Role      string `protobuf:"bytes,2,opt,name=role,proto3"       json:"role,omitempty"`
	ClientId  string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId    string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3"    json:"user_id,omitempty"`
	ContextId string `protobuf:"bytes,5,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
}

func (x *IntelligenceRequest) Reset()         {}
func (x *IntelligenceRequest) String() string  { return x.Query }
func (x *IntelligenceRequest) ProtoMessage()   {}

func (x *IntelligenceRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *IntelligenceRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *IntelligenceRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IntelligenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntelligenceRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

// IntelligenceResponse carries the agent's final answer and metadata.
type IntelligenceResponse struct {
	Answer   string `protobuf:"bytes,1,opt,name=answer,proto3"    json:"answer,omitempty"`
	ToolUsed string `protobuf:"bytes,2,opt,name=tool_used,json=toolUsed,proto3" json:"tool_used,omitempty"`
	Success  bool   `protobuf:"varint,3,opt,name=success,proto3"  json:"success,omitempty"`
}

func (x *IntelligenceResponse) Reset()         {}
func (x *IntelligenceResponse) String() string  { return x.Answer }
func (x *IntelligenceResponse) ProtoMessage()   {}

func (x *IntelligenceResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *IntelligenceResponse) GetToolUsed() string {
	if x != nil {
		return x.ToolUsed
	}
	return ""
}

func (x *IntelligenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}