// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Manually written stub matching intelligence.proto
// source: intelligence.proto

package pb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// IntelligenceServiceClient is the client API for IntelligenceService service.
type IntelligenceServiceClient interface {
	// Unified query endpoint — any authenticated user calls this.
	// The agent reads role, client_id, context_id to decide tool and scope.
	Ask(ctx context.Context, in *IntelligenceRequest, opts ...grpc.CallOption) (*IntelligenceResponse, error)
}

type intelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelligenceServiceClient(cc grpc.ClientConnInterface) IntelligenceServiceClient {
	return &intelligenceServiceClient{cc}
}

func (c *intelligenceServiceClient) Ask(ctx context.Context, in *IntelligenceRequest, opts ...grpc.CallOption) (*IntelligenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntelligenceResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntelligenceServiceServer is the server API for IntelligenceService service.
type IntelligenceServiceServer interface {
	// Unified query endpoint — any authenticated user calls this.
	Ask(context.Context, *IntelligenceRequest) (*IntelligenceResponse, error)
	mustEmbedUnimplementedIntelligenceServiceServer()
}

// UnimplementedIntelligenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntelligenceServiceServer struct{}

func (UnimplementedIntelligenceServiceServer) Ask(context.Context, *IntelligenceRequest) (*IntelligenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedIntelligenceServiceServer) mustEmbedUnimplementedIntelligenceServiceServer() {}

// UnsafeIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeIntelligenceServiceServer interface {
	mustEmbedUnimplementedIntelligenceServiceServer()
}

const IntelligenceService_Ask_FullMethodName = "/intelligence.IntelligenceService/Ask"

func RegisterIntelligenceServiceServer(s grpc.ServiceRegistrar, srv IntelligenceServiceServer) {
	s.RegisterService(&IntelligenceService_ServiceDesc, srv)
}

func _IntelligenceService_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntelligenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).Ask(ctx, req.(*IntelligenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntelligenceService_ServiceDesc is the grpc.ServiceDesc for IntelligenceService service.
var IntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "intelligence.IntelligenceService",
	HandlerType: (*IntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _IntelligenceService_Ask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intelligence.proto",
}